### ISSUE TITLE
AWS customer-facing topics for inclusion: Unsupported, EOL, deprecated images

### ISSUE THREAD

**Issue by marrek-az** [canonical/ubuntu-cloud-docs#197]
Some topics that are periodically/regularly surfaced by customer-facing teams:
- Are EOL images removed from AWS? Will I still be able to launch images the day after the end-of-support? (might want to talk about EC2 deprecated flag, and how it's not something you control, and how to work around it)
- Describe/point to docs that describe how to identify official Ubuntu images

I'm happy to contribute to the docs if desired. You know how to find me.

**Comment by rpocase** [comment]
thanks for logging this @marrek-az ! we're working through our deprecation/deletion policy internally and will link the docs when a PR is available.
