### ISSUE TITLE
docs: make the AWS nvidia docs generic for AWS

### ISSUE THREAD

**Issue by toabctl** [canonical/ubuntu-cloud-docs#228]
Currently this seems to be for a specific nvidia driver version but there is `ubuntu-drivers` and that should be used to install the correct driver for different hardware.

---
*Reported from: https://documentation.ubuntu.com/aws/en/latest/aws-how-to/instances/install-nvidia-drivers/*

**Comment by k-dimple** [comment]
@carlosbravoa if I remember correctly, you had to use the specific driver for a reason right?
