### ISSUE TITLE
doc: NVIDIA Device Plugin section is stale

### ISSUE THREAD

**Issue by mwpeterson** [canonical/ubuntu-cloud-docs#282]
Instructions reference v0.14.0 of the plugin. Current is v0.16.2. Applying the daemonset directly isn't recommended for production use:
> Note: This is a simple static daemonset meant to demonstrate the basic features of the nvidia-device-plugin. Please see the instructions below for [Deployment via helm](https://github.com/NVIDIA/k8s-device-plugin?tab=readme-ov-file#deployment-via-helm) when deploying the plugin in a production setting.

From https://github.com/NVIDIA/k8s-device-plugin?tab=readme-ov-file#enabling-gpu-support-in-kubernetes

Maybe update daemonset to the latest version, make it clear that this is the "quick-start" instructions, and provide the link to the docs for the Helm deployent? If I hadn't been double-checking versions of everything I would have gone to production with the daemonset, not knowing there was a better way. 

---
Document: aws-how-to/kubernetes/enable-gpus-on-eks.rst

**Comment by k-dimple** [comment]
Thanks for flagging these issues! We'll have an update soon.

**Comment by k-dimple** [comment]
@mwpeterson the instructions have been updated. Do let us know if something is still off, thanks!
