### ISSUE TITLE
docs: TYPE YOUR QUESTION HERE	ubuntu-2204-jammy-v20240801

### ISSUE THREAD

**Issue by saeedmushafi** [canonical/ubuntu-cloud-docs#283]

**Comment by k-dimple** [comment]
@saeedmushafi are you facing some issue with the Ubuntu on GCP docs? Could you give us more details about what you are looking for?

**Comment by saeedmushafi** [comment]
@k-dimple no thanks its fine

**Comment by k-dimple** [comment]
Thanks for your reply, I'll close the issue then!
