### ISSUE TITLE
docs: re "AWS services"

### ISSUE THREAD

**Issue by toabctl** [canonical/ubuntu-cloud-docs#59]
> The two main AWS services that use Ubuntu images are EC2 and EKS.

that doesn't sound good imo. EKS is just another service on AWS (beside the 100 other services they provide) and Canonical provides specific images for EKS (as we provide specific images for Workspaces)

---
*Reported from: https://canonical-aws.readthedocs-hosted.com/en/latest/*

**Comment by k-dimple** [comment]
I'll remove that portion and include EKS images as part of Canonical's offerings.
