### ISSUE TITLE
docs: Canonical’s offerings on AWS

### ISSUE THREAD

**Issue by toabctl** [canonical/ubuntu-cloud-docs#60]
I don't see `Pro` listed as an offering in `Canonical’s offerings on AWS`. Why not?

---
*Reported from: https://canonical-aws.readthedocs-hosted.com/en/latest/*

**Comment by k-dimple** [comment]
Good catch, this was based only on our internal docs. I'll add `Pro`, `Outposts` and `Pro with Support` too.
